**Лабораторна робота 1. Вступ до машинного навчання. Елементи лінійної алгебри.
Варіант 4**

In [2]:
import numpy as np
np.__version__

'2.0.2'

**Завдання 1.** Створіть одновимірний масив (вектор) з непарними числами від 1 до 19 та виведіть його значення.

In [3]:
vector = np.arange(1, 20, 2)
vector

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

**Завдання 2.** Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його послідовністю чисел, де кожне наступне число більше попереднього на 2, та виведіть його значення.

In [9]:
#arange  формує вектор з 9 елементів - послідовність елементів, де кожне число більше на 2, а reshape формує з вектора матрицю розміром 3*3.
matrix2 = np.arange(1, 19, 2).reshape(3, 3)
matrix2

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

**Завдання 3.** Створіть масив розміром 2x2, заповніть його випадковими цілими числами від -5 до 5 та виведіть його значення.

In [5]:
matrix3 = np.random.randint(-5, 6, size=(2, 2))
matrix3

array([[2, 3],
       [5, 4]])

**Завдання 4.** Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть максимальний елемент.

In [10]:
# виводимо матрицю 6*6, що заповнена випадковими дійсними числами в діапазоні від 0 до 1
matrix4 = np.random.rand(6, 6)
matrix4

array([[0.32791048, 0.25243209, 0.15405757, 0.22561868, 0.43350055,
        0.1982433 ],
       [0.49114947, 0.77973795, 0.66871869, 0.19338989, 0.86523304,
        0.46922316],
       [0.48787711, 0.12200416, 0.54113796, 0.72661358, 0.47664587,
        0.65315371],
       [0.60322303, 0.4824086 , 0.50689044, 0.94510133, 0.60292669,
        0.10197275],
       [0.76500851, 0.00399029, 0.34922926, 0.15005821, 0.93272856,
        0.93046024],
       [0.27027126, 0.95359148, 0.06781524, 0.27175334, 0.66124145,
        0.52224859]])

In [11]:
matrix4.max()

np.float64(0.9535914765565938)

**Завдання 5.** Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.

In [12]:
#перший одновимірний масив
matrix5_1 = np.random.randint(-5, 6, size=4)
matrix5_1

array([ 5,  0, -5, -4])

In [13]:
#другий одновимірний масив
matrix5_2 = np.random.randint(-5, 6, size=4)
matrix5_2

array([-5,  5, -1,  3])

In [14]:
#операція додавання
matrix5_1 + matrix5_2

array([ 0,  5, -6, -1])

In [15]:
#операція віднімання
matrix5_1 - matrix5_2

array([10, -5, -4, -7])

In [16]:
#операція поелементного множення
matrix5_1 * matrix5_2

array([-25,   0,   5, -12])

**Завдання 6.** Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 5 до 10 та знайдіть їх добуток.

In [21]:
#перша матриця
matrix6_1 = np.random.uniform(5, 10, size=(2, 2))
matrix6_1

array([[6.9289982 , 9.32038772],
       [6.12870607, 5.78482703]])

In [24]:
#друга матриця
matrix6_2 = np.random.uniform(5, 10, size=(2, 2))
matrix6_2

array([[8.16040365, 8.2430912 ],
       [7.11755471, 6.45279695]])

In [25]:
#добуток матриць
np.dot(matrix6_1, matrix6_2)

array([[122.88179176, 117.25893361],
       [ 91.18653822,  87.84779728]])

**Завдання 7.** Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [26]:
#перша матриця
matrix7_1 = np.random.randint(1, 6, size=(2, 3))
matrix7_1

array([[5, 5, 4],
       [1, 2, 1]])

In [27]:
#друга матриця
matrix7_2 = np.random.randint(1, 6, size=(3, 3))
matrix7_2

array([[3, 5, 1],
       [3, 5, 5],
       [1, 3, 5]])

In [28]:
#добуток матриць
np.dot(matrix7_1, matrix7_2)

array([[34, 62, 50],
       [10, 18, 16]])

**Завдання 8.** Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [34]:
#звичайна матриця
matrix8 = np.random.randint(1, 16, size=(3, 3))
matrix8

array([[11,  4,  6],
       [ 7,  8,  4],
       [13, 11, 12]])

In [35]:
#обернена матриця
np.linalg.inv(matrix8)

array([[ 0.18439716,  0.06382979, -0.11347518],
       [-0.11347518,  0.19148936, -0.0070922 ],
       [-0.09574468, -0.24468085,  0.21276596]])

**Завдання 9.** Створіть матрицю розміром 7x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [37]:
#матриця розміром 7x4
matrix9 = np.random.rand(7, 4)
matrix9

array([[0.27890981, 0.13805786, 0.09477045, 0.31356046],
       [0.66607087, 0.8072096 , 0.03510711, 0.61464454],
       [0.60403986, 0.52840069, 0.55284335, 0.29932871],
       [0.3916108 , 0.12439028, 0.42370662, 0.67726733],
       [0.16120199, 0.85429769, 0.12753267, 0.12179078],
       [0.368359  , 0.41975139, 0.93185031, 0.20174714],
       [0.78058639, 0.64786176, 0.9910387 , 0.91183013]])

In [38]:
#транспонована матриця
matrix9.T

array([[0.27890981, 0.66607087, 0.60403986, 0.3916108 , 0.16120199,
        0.368359  , 0.78058639],
       [0.13805786, 0.8072096 , 0.52840069, 0.12439028, 0.85429769,
        0.41975139, 0.64786176],
       [0.09477045, 0.03510711, 0.55284335, 0.42370662, 0.12753267,
        0.93185031, 0.9910387 ],
       [0.31356046, 0.61464454, 0.29932871, 0.67726733, 0.12179078,
        0.20174714, 0.91183013]])

**Завдання 10.** Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [40]:
#матриця розміром 3x4, що заповнена цілими числами від 1 до 10
matrix10 = np.random.randint(1, 11, size=(3, 4))
matrix10

array([[ 4,  2, 10, 10],
       [ 2,  1,  2,  2],
       [ 3,  7,  8,  1]])

In [39]:
#вектор розміром 4x1, що заповнений дійсними числами від 0 до 1
vector10 = np.random.rand(4, 1)
vector10

array([[0.21192352],
       [0.75352873],
       [0.25772775],
       [0.38367666]])

In [41]:
#добуток матриць
np.dot(matrix10, vector10)

array([[8.7687957 ],
       [2.46018461],
       [8.35597039]])

**Завдання 11.** Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [42]:
#матриця розміром 2x3, що заповнена дійсними числами від 0 до 1
matrix11 = np.random.rand(2, 3)
matrix11

array([[0.60714815, 0.20488455, 0.12064558],
       [0.32446673, 0.12486674, 0.31202213]])

In [43]:
#вектор розміром 3x1, що заповнений дійсними числами від 0 до 1
vector11 = np.random.rand(3, 1)
vector11

array([[0.96474985],
       [0.17055103],
       [0.22562969]])

In [44]:
#добуток матриць
np.dot(matrix11, vector11)

array([[0.64791058],
       [0.40472683]])

**Завдання 12.** Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення першої матриці до другої (поелементне ділення).

In [45]:
#перша матриця
matrix12_1 = np.random.randint(1, 11, size=(3, 4))
matrix12_1

array([[ 8,  4,  1,  3],
       [ 6,  8,  9,  5],
       [ 6, 10,  1,  9]])

In [46]:
#друга матриця
matrix12_2 = np.random.randint(1, 11, size=(3, 4))
matrix12_2

array([[ 6,  7,  2,  8],
       [10,  1,  9,  8],
       [ 6,  4, 10,  4]])

In [47]:
#відношення першої матриці до другої (поелементне ділення)
#оскільки матриці не містять елементів, що дорівнюють 0, то можемо просто ділити за допомогою "/"
matrix12_1 / matrix12_2

array([[1.33333333, 0.57142857, 0.5       , 0.375     ],
       [0.6       , 8.        , 1.        , 0.625     ],
       [1.        , 2.5       , 0.1       , 2.25      ]])

**Завдання 13.** Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму їх елементів.

In [49]:
#перша матриця
matrix13_1 = np.random.randint(1, 11, size=(5, 5))
matrix13_1

array([[ 4,  6,  6,  2,  5],
       [10,  4,  4,  3,  8],
       [ 7,  1, 10,  8,  5],
       [ 6,  2, 10,  7,  5],
       [ 6,  3,  6,  5,  6]])

In [50]:
#друга матриця
matrix13_2 = np.random.randint(1, 11, size=(5, 5))
matrix13_2

array([[ 6,  1,  5,  8,  9],
       [ 4,  7,  2,  1,  2],
       [ 1,  6,  8, 10,  7],
       [ 8,  3,  9,  6,  6],
       [ 8,  9,  2,  4,  9]])

In [53]:
#сума елементів першої матриці
sum1 = np.sum(matrix13_1)
sum1

np.int64(139)

In [54]:
#сума елементів другої матриці
sum2 = np.sum(matrix13_2)
sum2

np.int64(141)

In [55]:
#загальна сума елементів обох матриць
sum1 + sum2

np.int64(280)

**Завдання 14.** Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток елементів матриці.

In [57]:
#матриця розміром 3x3, що заповнена цілими числами від 1 до 10
matrix14 = np.random.randint(1, 11, size=(3, 3))
matrix14

array([[ 3, 10,  9],
       [ 2,  8, 10],
       [ 4,  4, 10]])

In [58]:
#добуток елементів матриці
np.prod(matrix14)

np.int64(6912000)

**Завдання 15.** Створіть матрицю розміром 6x6, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить середнє арифметичне значення елементів кожного рядка матриці.

In [60]:
#матриця розміром 6x6, що заповнена дійсними числами від -2 до 2
matrix15 = np.random.uniform(-2, 2, size=(6, 6))
matrix15

array([[ 0.13477648, -1.90072468,  0.92136148,  1.18118897,  1.70935603,
        -1.43366566],
       [ 0.43795209,  0.64639712, -1.762486  ,  1.48194113, -0.73816653,
        -1.25458272],
       [ 0.94574104,  0.93117719, -0.15496763,  0.9877557 ,  0.76873884,
         0.07685989],
       [ 0.40735058, -0.06343205, -1.44523637,  0.06800759, -1.8918255 ,
        -0.85399204],
       [ 0.90126129,  0.94351387,  1.4191488 , -1.7690714 , -0.15513408,
         1.43256521],
       [ 1.22672204, -0.67976326, -0.13798022, -1.71631759,  1.02282207,
        -1.30771645]])

In [66]:
mean = matrix15.mean(axis=1) #axis=1 означає, що ми обчислюємо середнє значення по рядкам
mean

array([ 0.10204877, -0.19815749,  0.59255084, -0.62985463,  0.46204728,
       -0.26537223])

In [68]:
mean.reshape(6,1) #перетворюємо вектор-рядок на вектор-стовпчик

array([[ 0.10204877],
       [-0.19815749],
       [ 0.59255084],
       [-0.62985463],
       [ 0.46204728],
       [-0.26537223]])

**Висновок:** Отже, під час виконання даної лабораторної роботи були закріплені навички роботи з одновимірними і багатовимірними масивами даних, що є важливим для подальшого вивчення методів і алгоритмів машинного навчання. Зокрема, було створено матриці різних розмірів, що заповнюються цілими або дійсними числами, знайдено їх обернені та транспоновані матриці, здійснено ряд математичних операцій над матрицями: додавання, віднімання, ділення, множення тощо. Також досліджено статистичний показник для однієї з матриць - середнє арифметичне значення елементів кожного рядка заданої матриці.